model:
  model_name: "gpt2"
  max_length: 512
  

data:
  train_path: "/Users/pushpita/Documents/ML Projects/Building_LLM_from_scratch/MiniAstroLM/data/judged_samples/train.jsonl"
  max_samples: 1000
training:
  batch_size: 2
  lr: 5.e-5
  max_steps: 2000
  weight_decay: 0.01
  seed: 42
  device: "mps"

output:
  output_dir: "/Users/pushpita/Documents/ML Projects/Building_LLM_from_scratch/MiniAstroLM/data/student"
